YOURPROJECTNAMEGOESHERE: Station Class Reference
Station Class Reference
#include <Station.h>
Public Member Functions
Station (const std::string &i_name, double i_price, const std::vector< unsigned int > &i_rentPrices)
unsigned int getOwner () const
method that returns the owner of the property
void printExtras () const
method that prints all the information about the Station
void resetExtras ()
method that resets the values of a property in case the game is reset
void payRent (PlayerManager &i_players)
method that does the action =p
~Station ()
default destructor
Public Member Functions inherited from Property
Property (const std::string &i_name, double i_price)
default constructor
void print () const
method that prints all the information about the Property
void reset ()
method that resets all the values of the Tile
virtual void action (PlayerManager &i_players)
method that does the action =p
virtual ~Property ()
default destructor
Public Member Functions inherited from Tile
Tile (const std::string &i_name)
default constructor
void setColour (const std::string &i_colour)
method that sets the colour of the tile
const std::string & getColour () const
method that gets the colour of the tile
virtual unsigned int getHousePrice () const
method that returns house price
virtual unsigned int getNumOfHouses () const
returns the number of houses a property has
virtual bool buildHouse ()
method that builds a house to a property
const std::string & getName () const
method that returns the name of the property
virtual ~Tile ()
default destructor
Private Attributes
std::vector< double > m_rentPrices
Additional Inherited Members
Protected Member Functions inherited from Property
void buyProperty (PlayerManager &i_players)
method to buy property
Protected Attributes inherited from Property
int m_owner
the owner of the the property, equals to -1 if it is not owned
const int m_price
the price of the property
bool m_isPropertyMortgaged
indicated whether the property is morgated or not,1 for morgated
Protected Attributes inherited from Tile
std::string m_colour
the colour of the tile
std::string m_name
the name of the tile i.e Piccadilly, Jail and Chance
Detailed Description
Definition at line 8 of file Station.h.
Constructor & Destructor Documentation
Station::Station (const std::string & i_name, double i_price, const std::vector< unsigned int > & i_rentPrices)
default constructor
Parameters:
[in] i_name,: the name of the tile
[in] i_price,: the price of the property
Definition at line 5 of file Station.cpp.
References m_rentPrices.
         :Property(i_name,i_price)
{
    m_rentPrices.resize(4);
    for(unsigned int i=0; i<4; ++i)
    {
        m_rentPrices[i] = i_rentPrices[i];
    }
}
Station::~Station ()
default destructor
Definition at line 62 of file Station.cpp.
{}
Member Function Documentation
unsigned int Station::getOwner () const virtual
method that returns the owner of the property
Implements Property.
Definition at line 37 of file Station.cpp.
References Property::m_owner.
{
    return m_owner;
}
void Station::payRent (PlayerManager & i_players) virtual
method that does the action =p
Parameters:
[in] i_player the player that have reached that specific tile
Implements Property.
Definition at line 43 of file Station.cpp.
References PlayerManager::addBalance(), Property::m_owner, m_rentPrices, PlayerManager::takeBalance(), and PlayerManager::withdrawGame().
{
    unsigned int rent = m_rentPrices[0];
    std::cout << "You have to pay " << rent << " for Rent\n";
    if(i_players.takeBalance(rent))
    {
        i_players.addBalance(rent,m_owner);
    }
    else
    {
        std::cout << "Player do not have enough money to pay";
        rent = i_players.withdrawGame();
        i_players.addBalance(rent);
    }
}
void Station::printExtras () const virtual
method that prints all the information about the Station
Implements Property.
Definition at line 19 of file Station.cpp.
References m_rentPrices.
{
    std::cout << "RENT PRICES: ";
    for(unsigned int i=0; i<m_rentPrices.size(); ++i)
    {
        std::cout << m_rentPrices[i] << " ";
    }
    std::cout << "\n-------------------------------------------------\n";
    std::cout << "\n";
}
void Station::resetExtras () virtual
method that resets the values of a property in case the game is reset
Implements Property.
Definition at line 31 of file Station.cpp.
{
}
Member Data Documentation
std::vector<double> Station::m_rentPrices private
Definition at line 43 of file Station.h.
The documentation for this class was generated from the following files:
Station.h
Station.cpp