YOURPROJECTNAMEGOESHERE: Board Class Reference
Board Class Reference
#include <Board.h>
Public Member Functions
Board ()
default contstructor
void print ()
method that prints the board
void print (unsigned int i_tile) const
method that prints a specific tile
void reset ()
method that resets the board
void action (PlayerManager &i_players)
method that perfoms an action
void buildHouses (PlayerManager &i_players)
method that allows the current Player to buy houses
const std::string & getTileName (unsigned int i_index) const
method that returns the name of the tile
~Board ()
default destructor
Private Member Functions
std::string readTilesName (const std::vector< std::string > &i_words, unsigned int *i_p)
method that read the name of the next tile
Private Attributes
GroupsManager m_groups
how the tiles relates to each other, separated in groups
CardsManager m_cards
the cards, community chest and chance
std::vector< Tile * > m_tiles
all the tiles of the board in the correct order
Static Private Attributes
static const unsigned int numOfTiles = 40
the number of tiles
Detailed Description
Definition at line 10 of file Board.h.
Constructor & Destructor Documentation
Board::Board ()
default contstructor
Definition at line 18 of file Board.cpp.
References GroupsManager::addTile(), m_cards, m_groups, m_tiles, and readTilesName().
{
  //  CardsManager::initialiseCards();
    // Corners
    std::ifstream bvhStream("Board");
    if (!bvhStream) {
        std::cout << "File Board not found. Game will terminate\n";
        exit (EXIT_FAILURE);
    }
    std::istream_iterator<std::string> bvhIt(bvhStream);
    std::istream_iterator<std::string> sentinel;
    std::vector<std::string> words(bvhIt,sentinel);
    m_tiles.resize(40);
    unsigned int i=0 , counter = 0;
    while(i<words.size()-3)
    {
        i++;
        const char flag = words[i++][0];
        unsigned int price = 0;
        std::string name, colour;
        int housePrice;
        std::vector<unsigned int> rentPrices;
        rentPrices.resize(6);
        switch(flag)
        {
        case 'c': //Card
            name  = readTilesName(words,&i);
            m_tiles[counter] = new GetACardTIle(name,m_cards);
            break;
        case 'o': //Order tax,jail,go,go to jail
        {
            const std::string flag = words[i++];
            if(flag=="p")
            {
                const unsigned int money =atoi(words[i++].c_str());
                name = readTilesName(words,&i);
                m_tiles[counter]=new Order(name,"p",money);
            }
            else
            {
                name = readTilesName(words,&i);
                m_tiles[counter] = new Order(name,flag);
            }
            break;
        }
        case 'p': // Property
        {
            const char secondFlag = words[i++][0];
            price = atoi(words[i++].c_str());
            switch(secondFlag)
            {
            case 'n': //Normal Property
            {
                housePrice = atoi(words[i++].c_str());
                for(unsigned int k=0; k<6; ++k)
                {
                    rentPrices[k] = atoi(words[i++].c_str());
                }
                colour = words[i++];
                name = readTilesName(words,&i);
                m_tiles[counter] =
                        new NormalProperty(name,price,housePrice,rentPrices);
                m_groups.addTile(colour,m_tiles[counter]);
                m_tiles[counter]->setColour(colour);
                break;
            }
            case 's': //Station
                for(unsigned int k=0; k<4; ++k)
                {
                    rentPrices[k] = atoi(words[i++].c_str());
                }
                name = readTilesName(words,&i);
                m_tiles[counter] = new Station(name,price,rentPrices);
                m_groups.addTile("station",m_tiles[counter]);
                break;
            case 'u' : // Works - Company
                for(unsigned int k=0; k<2; ++k)
                {
                    rentPrices[k] = atoi(words[i++].c_str());
                }
                name = readTilesName(words,&i);
                m_tiles[counter] = new Utility(name,price,rentPrices);
                m_groups.addTile("utility",m_tiles[counter]);
            break;
            default:
                break;
            }
            break;
        }
        default:
            std::cerr << "Wrong flag type.\n";
            exit(EXIT_FAILURE);
            break;
        }
        i++;
        counter++;
    }
}
Board::~Board ()
default destructor
Definition at line 170 of file Board.cpp.
References m_tiles, and numOfTiles.
{
   // CardsManager::destroyedAllCards();
    for (unsigned int i=0; i<numOfTiles; ++i)
    {
        delete m_tiles[i];
    }
}
Member Function Documentation
void Board::action (PlayerManager & i_players)
method that perfoms an action
Definition at line 124 of file Board.cpp.
References PlayerManager::getPosition(), and m_tiles.
{
    int currentTile = i_players.getPosition();
    m_tiles[currentTile]->action(i_players);
}
void Board::buildHouses (PlayerManager & i_players)
method that allows the current Player to buy houses
Definition at line 164 of file Board.cpp.
References GroupsManager::buildHouses(), and m_groups.
{
    m_groups.buildHouses(i_players);
}
const std::string & Board::getTileName (unsigned int i_index) const
method that returns the name of the tile
Definition at line 141 of file Board.cpp.
References m_tiles.
{
    return m_tiles[i_index]->getName();
}
void Board::print () inline
method that prints the board
Definition at line 20 of file Board.h.
References m_tiles.
                {
        for(unsigned int i=0; i<m_tiles.size();++i)
        {
            m_tiles[i]->print();
        }
    }
void Board::print (unsigned int i_tile) const
method that prints a specific tile
Parameters:
[in] i_tile tile to be printed
Definition at line 118 of file Board.cpp.
References m_tiles.
{
    m_tiles[i_tile]->print();
}
std::string Board::readTilesName (const std::vector< std::string > & i_words, unsigned int * i_p) private
method that read the name of the next tile
Definition at line 149 of file Board.cpp.
{
    std::string name = i_words[*io_p];
    *io_p = *io_p + 1;
    while(i_words[*io_p]!=".")
    {
        name+=" " + i_words[*io_p];
        *io_p = *io_p + 1;
    }
    return name;
}
void Board::reset ()
method that resets the board
Definition at line 131 of file Board.cpp.
References m_tiles, and numOfTiles.
{
    for(unsigned int i=0; i<numOfTiles; ++i)
    {
        m_tiles[i]->reset();
    }
}
Member Data Documentation
CardsManager Board::m_cards private
the cards, community chest and chance
Definition at line 72 of file Board.h.
GroupsManager Board::m_groups private
how the tiles relates to each other, separated in groups
Definition at line 57 of file Board.h.
std::vector<Tile *> Board::m_tiles private
all the tiles of the board in the correct order
Definition at line 76 of file Board.h.
const unsigned int Board::numOfTiles = 40 static private
the number of tiles
Definition at line 68 of file Board.h.
The documentation for this class was generated from the following files:
Board.h
Board.cpp