var annotated =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "Card", "class_card.html", "class_card" ],
    [ "CardChanceOrLoseMoney", "class_card_chance_or_lose_money.html", "class_card_chance_or_lose_money" ],
    [ "CardGetOutOfJail", "class_card_get_out_of_jail.html", "class_card_get_out_of_jail" ],
    [ "CardGoToJail", "class_card_go_to_jail.html", "class_card_go_to_jail" ],
    [ "CardMovePlayerBack", "class_card_move_player_back.html", "class_card_move_player_back" ],
    [ "CardMovePlayerToPosition", "class_card_move_player_to_position.html", "class_card_move_player_to_position" ],
    [ "CardReceiveMoney", "class_card_receive_money.html", "class_card_receive_money" ],
    [ "CardReceiveMoneyFromPlayers", "class_card_receive_money_from_players.html", "class_card_receive_money_from_players" ],
    [ "CardsManager", "class_cards_manager.html", "class_cards_manager" ],
    [ "CardStreetRepairs", "class_card_street_repairs.html", "class_card_street_repairs" ],
    [ "CardTakeMoney", "class_card_take_money.html", "class_card_take_money" ],
    [ "Dice", "class_dice.html", "class_dice" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GetACardTIle", "class_get_a_card_t_ile.html", "class_get_a_card_t_ile" ],
    [ "GroupOfProperties", "class_group_of_properties.html", "class_group_of_properties" ],
    [ "GroupsManager", "class_groups_manager.html", "class_groups_manager" ],
    [ "NormalProperty", "class_normal_property.html", "class_normal_property" ],
    [ "Order", "class_order.html", "class_order" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerManager", "class_player_manager.html", "class_player_manager" ],
    [ "Property", "class_property.html", "class_property" ],
    [ "Station", "class_station.html", "class_station" ],
    [ "Tile", "class_tile.html", "class_tile" ],
    [ "Utility", "class_utility.html", "class_utility" ]
];