YOURPROJECTNAMEGOESHERE: Game Class Reference
Game Class Reference
#include <Game.h>
Public Member Functions
Game ()
default constructor
void PlayGame ()
method that plays the game
void reset ()
method that resets a game
~Game ()
default destructor
Private Member Functions
void takeTurn ()
method that takes a turn
std::string readTilesName (const std::vector< std::string > &i_words, unsigned int *i_p)
method that read the name of the next tile
Private Attributes
Board m_board
the board of the game
PlayerManager m_players
all the Players of the Game
Dice m_dices
the game dice
Detailed Description
Definition at line 12 of file Game.h.
Constructor & Destructor Documentation
Game::Game ()
default constructor
Definition at line 11 of file Game.cpp.
{}
Game::~Game ()
default destructor
Definition at line 171 of file Game.cpp.
{
}
Member Function Documentation
void Game::PlayGame ()
method that plays the game
Definition at line 21 of file Game.cpp.
References Board::action(), Board::buildHouses(), PlayerManager::getBalance(), PlayerManager::getCurrentPlayer(), PlayerManager::getName(), PlayerManager::getNumOfPlayers(), Dice::getTotal(), PlayerManager::howManyPlayersAreStillOntheGame(), PlayerManager::isCurrentPlayerInJail(), Dice::isDouble(), m_board, m_dices, m_players, PlayerManager::movePositionBy(), PlayerManager::moveToNextPlayer(), Dice::print(), PlayerManager::printWinner(), Dice::roll(), PlayerManager::setJailed(), PlayerManager::takeBalance(), takeTurn(), and PlayerManager::withdrawGame().
{
    std::cout << "\nNow we will start the game.\n" << std::endl;
    unsigned int numOfContinuousDoubles = 0;
    std::vector<unsigned int >numOfTimesRollDicesInJail;
    numOfTimesRollDicesInJail.resize(m_players.getNumOfPlayers());
    for(unsigned int i=0; i<numOfTimesRollDicesInJail.size();++i)
    {
        numOfTimesRollDicesInJail[i]=0;
    }
    while(m_players.howManyPlayersAreStillOntheGame()>1)
    {
        if(m_players.isCurrentPlayerInJail())
        {
            if(numOfTimesRollDicesInJail[m_players.getCurrentPlayer()]!=3)
            {
                std::cout << "\nPlayer "<< m_players.getName() << " is in Jail!\n";
                std::cout << "Do you want to pay 50 and go? (y/n)";
                std::string yesOrNo;
                std::cin >> yesOrNo;
                if(yesOrNo=="y")
                {
                    numOfTimesRollDicesInJail[m_players.getCurrentPlayer()]=0;
                    if(!m_players.takeBalance(50))
                    {
                        std::cout<< "You do not have enough money to pay!\n";
                        std::cout<< "Press 'R' to roll the dices!\n";
                        while (yesOrNo!= "R")
{
                            std::cin >> yesOrNo;
                        }
                        numOfTimesRollDicesInJail[m_players.getCurrentPlayer()]++;
                        m_dices.roll();
                        m_dices.print();
                        if(m_dices.isDouble())
{
                            m_players.movePositionBy(m_dices.getTotal());
                            m_board.action(m_players);
                        }
                    }
                    else
                    {
                        m_players.setJailed(false);
                        takeTurn();
                    }
                }else
                {
                    std::cout<< "Press 'R' to roll the dices!\n";
                    while (yesOrNo!= "R")
                    {
                        std::cin >> yesOrNo;
                    }
                    numOfTimesRollDicesInJail[m_players.getCurrentPlayer()]++;
                    m_dices.roll();
                    m_dices.print();
                    if(m_dices.isDouble())
                    {
                        m_players.movePositionBy(m_dices.getTotal());
                        m_board.action(m_players);
                    }
                }
                m_players.moveToNextPlayer();
            }
            else
            {
                numOfTimesRollDicesInJail[m_players.getCurrentPlayer()]=0;
                std::cout << "You have to pay 50 and get out of Jail!\n";
                if(!m_players.takeBalance(50))
                {
                    std::cout << "You do not have enough money to pay!\n";
                    m_players.withdrawGame();
                    m_players.moveToNextPlayer();
                }
                else
                {
                    m_players.setJailed(false);
                    std::cout<< "Press 'R' to roll the dices!\n";
                    std::string answer="";
                    while (answer!= "R")
                    {
                        std::cin >> answer;
                    }
                    takeTurn();
                    m_players.moveToNextPlayer();
                }
            }
        }else
        {
            std::cin.clear();
            std::cin.ignore(INT_MAX, '\n');
            std::string answer;
            std::cout << "\n   ***  Player: " << m_players.getName()
                      << ",  Balance = " << m_players.getBalance() <<"  ***\n";
           std::cout  << "Press B to build houses, R to roll and play, or "
                      << " W to Withdraw the game \n";
           while(answer!="R"&& answer!="B" && answer!="W")
           {
               std::cin >> answer;
           }
            if(answer == "R")
            {
                takeTurn();
            }
            else if(answer == "W")
            {
                m_players.withdrawGame();
            }
            else  // buy houses
            {
                m_board.buildHouses(m_players);
                std::cout << "Press R to roll and play\n";
                while(answer!="R")
                {
                    std::cin >> answer;
                }
                takeTurn();
            }
            if(m_dices.isDouble())
            {
                if(numOfContinuousDoubles==3)
                {
                    m_players.setJailed(true);
                    numOfContinuousDoubles = 0;
                }
                numOfContinuousDoubles++;
                m_board.action(m_players);
            }
            else
            {
                m_board.action(m_players);
                m_players.moveToNextPlayer();
            }
        }
    }
    m_players.printWinner();
}
std::string Game::readTilesName (const std::vector< std::string > & i_words, unsigned int * i_p) private
method that read the name of the next tile
void Game::reset ()
method that resets a game
Definition at line 15 of file Game.cpp.
{
}
void Game::takeTurn () private
method that takes a turn
Definition at line 161 of file Game.cpp.
References PlayerManager::getCurrentPlayersPosition(), Dice::getTotal(), m_board, m_dices, m_players, PlayerManager::movePositionBy(), Board::print(), Dice::print(), and Dice::roll().
{
    m_dices.roll();
    m_dices.print();
    m_players.movePositionBy(m_dices.getTotal());
    std::cout << "You have reach the following Tile:\n";
    m_board.print(m_players.getCurrentPlayersPosition());
}
Member Data Documentation
Board Game::m_board private
the board of the game
Definition at line 41 of file Game.h.
Dice Game::m_dices private
the game dice
Definition at line 56 of file Game.h.
PlayerManager Game::m_players private
all the Players of the Game
Definition at line 52 of file Game.h.
The documentation for this class was generated from the following files:
Game.h
Game.cpp