YOURPROJECTNAMEGOESHERE: Utility Class Reference
Utility Class Reference
#include <Utility.h>
Public Member Functions
Utility (const std::string &i_name, double i_price, const std::vector< unsigned int > &i_rentPrices)
default constructor
unsigned int getOwner () const
method that returns the owner of the property
void payRent (PlayerManager &i_players)
method that does the action =p
void resetExtras ()
method that resets all its values to the default ones
void printExtras () const
method that prints all the information about the properties
~Utility ()
default destructor
Public Member Functions inherited from Property
Property (const std::string &i_name, double i_price)
default constructor
void print () const
method that prints all the information about the Property
void reset ()
method that resets all the values of the Tile
virtual void action (PlayerManager &i_players)
method that does the action =p
virtual ~Property ()
default destructor
Public Member Functions inherited from Tile
Tile (const std::string &i_name)
default constructor
void setColour (const std::string &i_colour)
method that sets the colour of the tile
const std::string & getColour () const
method that gets the colour of the tile
virtual unsigned int getHousePrice () const
method that returns house price
virtual unsigned int getNumOfHouses () const
returns the number of houses a property has
virtual bool buildHouse ()
method that builds a house to a property
const std::string & getName () const
method that returns the name of the property
virtual ~Tile ()
default destructor
Private Attributes
std::vector< unsigned int > m_rentPrices
how many times you pay the total of the dices
Additional Inherited Members
Protected Member Functions inherited from Property
void buyProperty (PlayerManager &i_players)
method to buy property
Protected Attributes inherited from Property
int m_owner
the owner of the the property, equals to -1 if it is not owned
const int m_price
the price of the property
bool m_isPropertyMortgaged
indicated whether the property is morgated or not,1 for morgated
Protected Attributes inherited from Tile
std::string m_colour
the colour of the tile
std::string m_name
the name of the tile i.e Piccadilly, Jail and Chance
Detailed Description
Definition at line 5 of file Utility.h.
Constructor & Destructor Documentation
Utility::Utility (const std::string & i_name, double i_price, const std::vector< unsigned int > & i_rentPrices)
default constructor
Definition at line 5 of file Utility.cpp.
References m_rentPrices.
         :Property(i_name,i_price)
{
    m_rentPrices.resize(2);
    for(unsigned int i=0; i<2; ++i)
    {
        m_rentPrices[0] = i_rentPrices[0];
        m_rentPrices[1] = i_rentPrices[1];
    }
}
Utility::~Utility ()
default destructor
Definition at line 57 of file Utility.cpp.
{}
Member Function Documentation
unsigned int Utility::getOwner () const virtual
method that returns the owner of the property
Implements Property.
Definition at line 40 of file Utility.cpp.
References Property::m_owner.
{
    return m_owner;
}
void Utility::payRent (PlayerManager & i_players) virtual
method that does the action =p
Parameters:
[in] i_player the player that have reached that specific tile
Implements Property.
Definition at line 20 of file Utility.cpp.
References PlayerManager::addBalance(), Dice::getTotal(), Property::m_owner, m_rentPrices, Dice::roll(), PlayerManager::takeBalance(), and PlayerManager::withdrawGame().
{
    Dice dice;
    dice.roll();
    const unsigned int amountTobePaid = dice.getTotal() *m_rentPrices[0];
    if(i_players.takeBalance(amountTobePaid))
    {
        std::cout << "You have paid " << amountTobePaid << " rent.\n";
        i_players.addBalance(amountTobePaid,m_owner);
    }
    else
    {
        std::cout << "You do not have enough money to pay!\n";
        i_players.withdrawGame();
    }
}
void Utility::printExtras () const virtual
method that prints all the information about the properties
Implements Property.
Definition at line 46 of file Utility.cpp.
{
    std::cout << "-------------------------------------------------\n";
}
void Utility::resetExtras () virtual
method that resets all its values to the default ones
Implements Property.
Definition at line 52 of file Utility.cpp.
{
}
Member Data Documentation
std::vector<unsigned int> Utility::m_rentPrices private
how many times you pay the total of the dices
Definition at line 43 of file Utility.h.
The documentation for this class was generated from the following files:
Utility.h
Utility.cpp