YOURPROJECTNAMEGOESHERE: Order Class Reference
Order Class Reference
#include <Order.h>
Public Member Functions
Order (const std::string &i_name, const std::string &flag)
default constructor
Order (const std::string &i_name, const std::string &flag, unsigned int i_money)
default constructor
void print () const
method that prints all the information about the Order Tile
void reset ()
method that resets all its values to the default ones
void action (PlayerManager &i_players)
method that does the action =p
~Order ()
default destructor
Public Member Functions inherited from Tile
Tile (const std::string &i_name)
default constructor
void setColour (const std::string &i_colour)
method that sets the colour of the tile
const std::string & getColour () const
method that gets the colour of the tile
virtual unsigned int getOwner () const
method that returns the owner of a property
virtual unsigned int getHousePrice () const
method that returns house price
virtual unsigned int getNumOfHouses () const
returns the number of houses a property has
virtual bool buildHouse ()
method that builds a house to a property
const std::string & getName () const
method that returns the name of the property
virtual ~Tile ()
default destructor
Private Attributes
std::string m_flag
indicates action to be perform
unsigned int m_money
amount of money in case money has to be paid
Additional Inherited Members
Protected Attributes inherited from Tile
std::string m_colour
the colour of the tile
std::string m_name
the name of the tile i.e Piccadilly, Jail and Chance
Detailed Description
Definition at line 6 of file Order.h.
Constructor & Destructor Documentation
Order::Order (const std::string & i_name, const std::string & flag)
default constructor
Parameters:
[in] i_name,: the name of the tile
Definition at line 4 of file Order.cpp.
         :Tile(i_name),
          m_flag(flag),
          m_money(0)
{
}
Order::Order (const std::string & i_name, const std::string & flag, unsigned int i_money)
default constructor
Parameters:
[in] i_name,: the name of the tile
[in] i_money,: money that needs to be paid
Definition at line 14 of file Order.cpp.
             :Tile(i_name),
              m_flag(flag),
              m_money(i_money)
{
}
Order::~Order ()
default destructor
Definition at line 66 of file Order.cpp.
{}
Member Function Documentation
void Order::action (PlayerManager & i_players) virtual
method that does the action =p
Parameters:
[in] i_player the player that have reached that specific tile
Implements Tile.
Definition at line 37 of file Order.cpp.
References PlayerManager::getName(), m_flag, m_money, PlayerManager::setJailed(), and PlayerManager::takeBalance().
{
    if(m_flag=="p") // pay money
    {
        std::cout << i_players.getName() << " has to pay " << m_money << "\n";
        i_players.takeBalance(m_money);
    }
    else if(m_flag=="j") // go to jail
    {
        std::cout << "You are going to JAIL!\n";
        i_players.setJailed(true);
    }
    else if (m_flag == "f") // free parking, go, or visiting jail
    {
    }
    else
    {
        //wrong flag
    }
}
void Order::print () const virtual
method that prints all the information about the Order Tile
Reimplemented from Tile.
Definition at line 25 of file Order.cpp.
References m_flag, m_money, and Tile::m_name.
{
    std::cout << "-------------------------------------------------\n";
    std::cout << "Tile's name: " << m_name << "\n";
    if( m_flag == "p")
    {
        std::cout << "Amount to be paid: " << m_money << "\n";
    }
    std::cout << "-------------------------------------------------\n\n";
}
void Order::reset () virtual
method that resets all its values to the default ones
Implements Tile.
Definition at line 61 of file Order.cpp.
{
}
Member Data Documentation
std::string Order::m_flag private
indicates action to be perform
Definition at line 46 of file Order.h.
unsigned int Order::m_money private
amount of money in case money has to be paid
Definition at line 50 of file Order.h.
The documentation for this class was generated from the following files:
Order.h
Order.cpp