YOURPROJECTNAMEGOESHERE: PlayerManager Class Reference
PlayerManager Class Reference
#include <PlayerManager.h>
Public Member Functions
PlayerManager ()
default constructor
PlayerManager (unsigned int i_numOfPlayers)
constructor
unsigned int getCurrentPlayersPosition () const
method that returns the position on the board of the current player
unsigned int howManyPlayersAreStillOntheGame () const
method that returns number of players that are still on the game
void setPlayers (unsigned int i_numOfPlayers)
set the number of Players and there game
void printWinner () const
method that prints all players that are still on the game starting with the person that owns mos
void resetAllPlayers ()
reset Players
void moveToNextPlayer ()
method that changes the current player to the next player
unsigned int getBalance ()
method that returns the Balance of the Player
bool takeBalance (unsigned int i_amount)
takes an amount of money from the balance of the Player
void addBalance (unsigned int i_amount)
method that adds an amount of money to the balance of the Player
unsigned int withdrawGame ()
method that the current player quits the game
void addBalance (unsigned int i_amount, unsigned int i_player)
method that adds an amount of money to a specific Player
unsigned int getPosition () const
method that returns the current position of the current Player
void movePositionBy (unsigned int i_amount)
method that moves the current player to a new position
void setPosition (unsigned int i_position)
method that sets the positions of the current player
void setJailed (bool jailed)
method that sends the current player to jail
unsigned int getCurrentPlayer () const
method that returns the current player
const std::string & getName () const
method that returns the name of the current Player
unsigned int getMoneyFromEachPlayer (unsigned int i_amount)
method that gets an amount of money from each player
bool isCurrentPlayerInJail () const
method tha returns true if current Player is in Jail
unsigned int getNumOfPlayers () const
method that returns the number of Players
~PlayerManager ()
default destructor
Private Attributes
std::vector< Player > m_players
all the Players of the game
unsigned int m_currentPlayer
the number of the current Player
unsigned int m_numOfLoosers
num of players that have lost the game
Dice m_dices
the dices
Detailed Description
Definition at line 7 of file PlayerManager.h.
Constructor & Destructor Documentation
PlayerManager::PlayerManager ()
default constructor
Definition at line 10 of file PlayerManager.cpp.
References m_players, and setPlayers().
         :m_currentPlayer(0),
          m_numOfLoosers(0)
{
    srand((unsigned)time(0));
    unsigned int numPlayers = 2;
    std::cout << "Enter number of players (2 - 6): ";
    std::cin >> numPlayers;
    while (numPlayers < 2 || numPlayers > 6) {
        std::cin.clear();
        std::cin.ignore(INT_MAX, '\n');
        std::cout << "Please enter a number between 2 and 6: ";
        std::cin >> numPlayers;
    }
    m_players.resize(numPlayers);
    setPlayers(numPlayers);
}
PlayerManager::PlayerManager (unsigned int i_numOfPlayers)
constructor
Parameters:
[in] i_numOfPlayers,: how many players are playing
Definition at line 29 of file PlayerManager.cpp.
References setPlayers().
         :m_currentPlayer(0),
          m_numOfLoosers(0)
{
    setPlayers(i_numOfPlayers);
}
PlayerManager::~PlayerManager ()
default destructor
Definition at line 262 of file PlayerManager.cpp.
{}
Member Function Documentation
void PlayerManager::addBalance (unsigned int i_amount)
method that adds an amount of money to the balance of the Player
Definition at line 190 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    m_players[m_currentPlayer].m_balance+=i_amount;
}
void PlayerManager::addBalance (unsigned int i_amount, unsigned int i_player)
method that adds an amount of money to a specific Player
Parameters:
[in] i_amount,: amount to be added
[in] i_player,: the player that gets the money
Definition at line 196 of file PlayerManager.cpp.
References m_players.
{
    m_players[i_player].m_balance+=i_amount;
}
unsigned int PlayerManager::getBalance ()
method that returns the Balance of the Player
Definition at line 170 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    return m_players[m_currentPlayer].m_balance;
}
unsigned int PlayerManager::getCurrentPlayer () const
method that returns the current player
Definition at line 227 of file PlayerManager.cpp.
References m_currentPlayer.
{
    return m_currentPlayer;
}
unsigned int PlayerManager::getCurrentPlayersPosition () const
method that returns the position on the board of the current player
Definition at line 122 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
   return m_players[m_currentPlayer].m_position;
}
unsigned int PlayerManager::getMoneyFromEachPlayer (unsigned int i_amount)
method that gets an amount of money from each player
Parameters:
[in] i_amount amount to be removed from players
Definition at line 233 of file PlayerManager.cpp.
References m_players, and takeBalance().
{
    unsigned int money=0;
    for(unsigned int i=0; i<m_players.size();++i)
    {
        if(m_players[i].takeBalance(i_amount))
        {
            money+=i_amount;
        }
        else
        {
            std::cout << m_players[i].m_name <<
                      " does not have enough money to pay " << i_amount <<"\n";
        }
    }
    return money;
}
const std::string & PlayerManager::getName () const
method that returns the name of the current Player
Definition at line 164 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    return m_players[m_currentPlayer].m_name;
}
unsigned int PlayerManager::getNumOfPlayers () const
method that returns the number of Players
Definition at line 38 of file PlayerManager.cpp.
References m_players.
{
    return m_players.size();
}
unsigned int PlayerManager::getPosition () const
method that returns the current position of the current Player
Definition at line 202 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    return m_players[m_currentPlayer].m_position;
}
unsigned int PlayerManager::howManyPlayersAreStillOntheGame () const
method that returns number of players that are still on the game
Definition at line 128 of file PlayerManager.cpp.
References m_players.
{
    unsigned int num = 0;
    for(unsigned int i=0; i<m_players.size(); ++i)
    {
        if(m_players[i].m_balance>0)
        {
            num+=1;
        }
    }
    return num;
}
bool PlayerManager::isCurrentPlayerInJail () const
method tha returns true if current Player is in Jail
Definition at line 142 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    return m_players[m_currentPlayer].m_isJailed;
}
void PlayerManager::movePositionBy (unsigned int i_amount)
method that moves the current player to a new position
Parameters:
[in] i_amount how many tiles the current Player will be moved
Definition at line 208 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    unsigned int oldPosition = m_players[m_currentPlayer].m_position;
    m_players[m_currentPlayer].m_position =
            (m_players[m_currentPlayer].m_position + i_amount) % 40;
    if (m_players[m_currentPlayer].m_position < oldPosition) {
        std::cout<< "You passed from GO. Get 200\n";
        m_players[m_currentPlayer].m_balance += 200;
    }
}
void PlayerManager::moveToNextPlayer ()
method that changes the current player to the next player
Definition at line 148 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    m_currentPlayer = (m_currentPlayer+1)%m_players.size();
    int numOfPlayers = m_players.size();
    while(m_players[m_currentPlayer].m_balance==0)
    {
        m_currentPlayer = (m_currentPlayer+1)%m_players.size();
        numOfPlayers--;
        if(numOfPlayers==0)
        {
            break;
        }
    }
}
void PlayerManager::printWinner () const
method that prints all players that are still on the game starting with the person that owns mos
Definition at line 91 of file PlayerManager.cpp.
References m_players.
{
    std::string winner=m_players[0].m_name;
    unsigned int maxPossesionsValue = 0;
    for(unsigned int i=0; i<m_players.size(); ++i)
    {
        if(m_players[i].m_balance>0)
        {
            const unsigned int currentPossesionValues =
                m_players[i].getPossessionsValue();
            if(maxPossesionsValue<currentPossesionValues)
            {
                maxPossesionsValue = currentPossesionValues;
                winner = m_players[i].m_name;
            }
        }
    }
    std::cout << "The winner is " << winner << " and their possessions are worth "
              << maxPossesionsValue << "\n";
}
void PlayerManager::resetAllPlayers ()
reset Players
Definition at line 113 of file PlayerManager.cpp.
References m_players.
{
    for(unsigned int i=0; i<m_players.size(); ++i)
    {
        m_players[i].reset();
    }
}
void PlayerManager::setJailed (bool jailed)
method that sends the current player to jail
Definition at line 252 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    m_players[m_currentPlayer].m_isJailed = jailed;
    if (jailed) {
        m_players[m_currentPlayer].m_isJailed = 4;
        m_players[m_currentPlayer].m_position = 10;
    }
}
void PlayerManager::setPlayers (unsigned int i_numOfPlayers)
set the number of Players and there game
Parameters:
[in] i_numOfPlayers,: how many players are playing
Definition at line 44 of file PlayerManager.cpp.
References Dice::getTotal(), m_currentPlayer, m_dices, m_players, and Dice::roll().
{
    m_players.resize(i_numOfPlayers);
    std::string currentName;
    for (unsigned int i=0;i<i_numOfPlayers;i++) {
        std::cout << "What's your name, player " << i+1 << "? ";
        std::cin >> currentName;
        m_players[i].setName(currentName);
    }
    std::cout << std::endl;
    std::cout << "Now we'll roll the dice to see who goes first"
              << std::endl;
    int oldwinner = 0;
    int winner = 0;
    int windex = -1;
    std::cin.clear();
    std::cin.ignore(INT_MAX, '\n');
    for (unsigned int i=0;i<m_players.size();i++) {
        std::cout << "Press ENTER to roll, " << m_players[i].m_name
                  << std::endl;
        std::cin.get();
        m_dices.roll();
        winner = m_dices.getTotal();
        std::cout << m_players[i].m_name << " rolled: " << winner
                  << std::endl <<std::endl;
        if (winner > oldwinner) windex = i;
        oldwinner = winner;
    }
    std::cout << m_players[windex].m_name << " goes first." << std::endl;
    m_currentPlayer = windex;
    std::cout << std::endl;
}
void PlayerManager::setPosition (unsigned int i_position)
method that sets the positions of the current player
Parameters:
[in] i_position the new Position of the current Player
Definition at line 221 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    m_players[m_currentPlayer].m_position=i_position;
}
bool PlayerManager::takeBalance (unsigned int i_amount)
takes an amount of money from the balance of the Player
Definition at line 176 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    if(m_players[m_currentPlayer].m_balance<i_amount )
    {
        return false;
    }
    else
    {
        m_players[m_currentPlayer].m_balance -= i_amount;
        return true;
    }
}
unsigned int PlayerManager::withdrawGame ()
method that the current player quits the game
it returns how much he owns in case he have to pay someone
Definition at line 83 of file PlayerManager.cpp.
References m_currentPlayer, and m_players.
{
    const unsigned int balance = m_players[m_currentPlayer].m_balance;
    m_players[m_currentPlayer].m_balance = 0;
    return balance;
}
Member Data Documentation
unsigned int PlayerManager::m_currentPlayer private
the number of the current Player
Definition at line 121 of file PlayerManager.h.
Dice PlayerManager::m_dices private
the dices
Definition at line 129 of file PlayerManager.h.
unsigned int PlayerManager::m_numOfLoosers private
num of players that have lost the game
Definition at line 125 of file PlayerManager.h.
std::vector<Player> PlayerManager::m_players private
all the Players of the game
Definition at line 117 of file PlayerManager.h.
The documentation for this class was generated from the following files:
PlayerManager.h
PlayerManager.cpp