YOURPROJECTNAMEGOESHERE: CardMovePlayerToPosition Class Reference
CardMovePlayerToPosition Class Reference
#include <CardMovePlayerToPosition.h>
Public Member Functions
CardMovePlayerToPosition (unsigned int i_position)
default constractor
void action (PlayerManager &i_players)
method that performs the action associated with that card
~CardMovePlayerToPosition ()
default destructor
Public Member Functions inherited from Card
Card ()
default constructor
void print () const
method that prints the card
virtual ~Card ()
default destructor
Private Attributes
int m_newPosition
the new position of the player
Detailed Description
Definition at line 6 of file CardMovePlayerToPosition.h.
Constructor & Destructor Documentation
CardMovePlayerToPosition::CardMovePlayerToPosition (unsigned int i_position)
default constractor
Definition at line 4 of file CardMovePlayerToPosition.cpp.
         :m_newPosition(i_position)
{
}
CardMovePlayerToPosition::~CardMovePlayerToPosition ()
default destructor
Definition at line 20 of file CardMovePlayerToPosition.cpp.
{
}
Member Function Documentation
void CardMovePlayerToPosition::action (PlayerManager & i_players) virtual
method that performs the action associated with that card
Implements Card.
Definition at line 11 of file CardMovePlayerToPosition.cpp.
References PlayerManager::getName(), PlayerManager::getPosition(), m_newPosition, and PlayerManager::setPosition().
{
    i_players.setPosition(m_newPosition);
    std::cout<< "Move " << i_players.getName() << " to " << i_players.getPosition() << " position." << std::endl;
}
Member Data Documentation
int CardMovePlayerToPosition::m_newPosition private
the new position of the player
Definition at line 26 of file CardMovePlayerToPosition.h.
The documentation for this class was generated from the following files:
CardMovePlayerToPosition.h
CardMovePlayerToPosition.cpp