YOURPROJECTNAMEGOESHERE: Property Class Reference
Property Class Reference
#include <Property.h>
Public Member Functions
Property (const std::string &i_name, double i_price)
default constructor
void print () const
method that prints all the information about the Property
void reset ()
method that resets all the values of the Tile
virtual unsigned int getOwner () const =0
method that returns the owner of the property
virtual void action (PlayerManager &i_players)
method that does the action =p
virtual ~Property ()
default destructor
Public Member Functions inherited from Tile
Tile (const std::string &i_name)
default constructor
void setColour (const std::string &i_colour)
method that sets the colour of the tile
const std::string & getColour () const
method that gets the colour of the tile
virtual unsigned int getHousePrice () const
method that returns house price
virtual unsigned int getNumOfHouses () const
returns the number of houses a property has
virtual bool buildHouse ()
method that builds a house to a property
const std::string & getName () const
method that returns the name of the property
virtual ~Tile ()
default destructor
Protected Member Functions
void buyProperty (PlayerManager &i_players)
method to buy property
Protected Attributes
int m_owner
the owner of the the property, equals to -1 if it is not owned
const int m_price
the price of the property
bool m_isPropertyMortgaged
indicated whether the property is morgated or not,1 for morgated
Protected Attributes inherited from Tile
std::string m_colour
the colour of the tile
std::string m_name
the name of the tile i.e Piccadilly, Jail and Chance
Private Member Functions
virtual void resetExtras ()=0
method that resets the values of any extra members of property
virtual void printExtras () const =0
method that prints any extra a property may have, ie: houses
virtual void payRent (PlayerManager &i_players)=0
method that the current player pays rent to the owner
Detailed Description
Definition at line 6 of file Property.h.
Constructor & Destructor Documentation
Property::Property (const std::string & i_name, double i_price)
default constructor
Parameters:
[in] i_name,: the name of the tile param[in] i_price: the price of the property
Definition at line 4 of file Property.cpp.
         :Tile(i_name),
    m_owner(-1),
    m_price(i_price),
    m_isPropertyMortgaged(0)
{
}
Property::~Property () virtual
default destructor
Definition at line 82 of file Property.cpp.
{}
Member Function Documentation
void Property::action (PlayerManager & i_players) virtual
method that does the action =p
Parameters:
[in] i_player the player that have reached that specific tile
Implements Tile.
Definition at line 65 of file Property.cpp.
References buyProperty(), PlayerManager::getCurrentPlayer(), m_owner, and payRent().
{
    if (m_owner == -1)
    {
        this->buyProperty(i_players);
    }
    else
    {
        if(m_owner!=(int)i_players.getCurrentPlayer())
        {
            this->payRent(i_players);
        }
    }
}
void Property::buyProperty (PlayerManager & i_players) protected
method to buy property
Definition at line 33 of file Property.cpp.
References PlayerManager::getCurrentPlayer(), m_owner, m_price, and PlayerManager::takeBalance().
{
    char response;
    std::cout << "Would you like to buy this property? (y/n): ";
    std::cin >> response;
    while ((response != 'y') && (response != 'n')){
            std::cout << std::endl << "Please type 'y' or 'n': ";
            std::cin >> response;
            std::cout << response;
    }
    if (response == 'y') {
        if(i_players.takeBalance(m_price))
        {
            m_owner = i_players.getCurrentPlayer();
        }
        else
        {
            std::cout<< "Player does not have enough money!\n";
        }
    }
}
virtual unsigned int Property::getOwner () const pure virtual
method that returns the owner of the property
Reimplemented from Tile.
Implemented in NormalProperty, Station, and Utility.
virtual void Property::payRent (PlayerManager & i_players) private pure virtual
method that the current player pays rent to the owner
Implemented in NormalProperty, Station, and Utility.
void Property::print () const virtual
method that prints all the information about the Property
Reimplemented from Tile.
Definition at line 15 of file Property.cpp.
References Tile::m_colour, m_isPropertyMortgaged, Tile::m_name, m_price, and printExtras().
{
    std::cout << "-------------------------------------------------\n";
    std::cout << "Tile's name: "    << m_name    << "\n"
              << "Tiles's colour: " << m_colour  << "\n"
              << "Price:       "    << m_price   << "\n";
    if(m_isPropertyMortgaged)
    {
        std::cout << "Mortgaged:   yes\n\n";
    }
    else
    {
        std::cout << "Mortgaged:   no\n";
    }
    printExtras();
}
virtual void Property::printExtras () const private pure virtual
method that prints any extra a property may have, ie: houses
Implemented in Utility, Station, and NormalProperty.
void Property::reset () virtual
method that resets all the values of the Tile
Implements Tile.
Definition at line 57 of file Property.cpp.
References m_isPropertyMortgaged, m_owner, and resetExtras().
{
    m_owner = -1;
    m_isPropertyMortgaged = 0;
    this->resetExtras();
}
virtual void Property::resetExtras () private pure virtual
method that resets the values of any extra members of property
Implemented in NormalProperty, Station, and Utility.
Member Data Documentation
bool Property::m_isPropertyMortgaged protected
indicated whether the property is morgated or not,1 for morgated
Definition at line 67 of file Property.h.
int Property::m_owner protected
the owner of the the property, equals to -1 if it is not owned
Definition at line 59 of file Property.h.
const int Property::m_price protected
the price of the property
Definition at line 63 of file Property.h.
The documentation for this class was generated from the following files:
Property.h
Property.cpp